Router
marclassort/Blog-PHP-Marc-Lassort pull request #1
Opened 2021-07-26 11:30 UTC by marclassort

The PR contains the implementation of the router, the routes, the main front and back-end templates, the controllers, managers and entities at a basic level.

2021-07-28 22:35 UTC, Fonctionnaire requested changes
Il faut que tu corriges les bugs/code smells de SC.

2021-07-30 13:01 UTC, marclassort commented
> Il faut que tu corriges les bugs/code smells de SC.

C'est fait ! J'attends ton retour pour merger sur la branche main. Merci d'avance.

2021-07-30 17:09 UTC, Fonctionnaire requested changes
Modifie le construct de l'entité User, et ça sera bon.

2021-07-30 17:09 UTC, Fonctionnaire commented on src/Entity/User.php
> +    public function __construct(string $un, string $fn, string $ln, string $pn, string $e, string $p, array $r)
Ca ne sert à rien. Ajout ici l'hydratation comme dans tes autres entités.

2021-07-30 17:42 UTC, Fonctionnaire approved these changes

2021-07-30 17:43 UTC, merged